### ISSUE TITLE
Add a Flow integration template

### ISSUE THREAD

**Issue by smol-ninja** [sablier-labs/lockup-integration-template#12]

**Comment by smol-ninja** [comment]
Given [this argument](https://github.com/sablier-labs/sablier-integration-template/issues/11#issuecomment-2478322038):

> the idea behind this repo is to simply fork it and start from scratch with some default things when integrating us (repo structure, NPM packages, etc.)

Shouldn't there be a separate repo as `flow-integration-template` and then rename this to `lockup-integration-template`? Otherwise user would have to fork it and then remove either flow or lockup from this repo before start working on it. Or is it OK to have both the protocols mentioned in this repo? cc @sablier-labs/solidity

**Comment by PaulRBerg** [comment]
Great idea @smol-ninja.

The name of the contracts in each repo should be `LockupStreamCreator` and `FlowStreamCreator`.

**Comment by smol-ninja** [comment]
Resolved in [51a601](https://github.com/sablier-labs/flow-integration-template/commit/51a6018d9ff9056718eec54ec459c55620942a76). I skipped creating a PR in the [Flow integration repo](https://github.com/sablier-labs/flow-integration-template) since its a new repo so all of it should be reviewed.
